version: "3.8"
services:
  golang:
    image: golang:1.15.6-alpine3.12
    networks:
    - varnish_clean_cache
    container_name: golang
  redis:
    image: redis:6.0.9-alpine
    ports:
    - 6379:6379
    networks:
    - varnish_clean_cache
    container_name: redis

networks:
  varnish_clean_cache:
    name: varnish_clean_cache